In [48]:
import pandas as pd

holiday_events = pd.read_csv('data/holidays_events.csv', parse_dates=['date'])
oil = pd.read_csv('data/oil.csv', parse_dates=['date'])
stores = pd.read_csv('data/stores.csv')
transactions = pd.read_csv('data/transactions.csv', parse_dates=['date'])
train_data = pd.read_csv('data/train.csv', parse_dates=['date'])
test_data = pd.read_csv('data/test.csv', parse_dates=['date'])

In [49]:
oil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   datetime64[ns]
 1   dcoilwtico  1175 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 19.2 KB

In [50]:
oil['dcoilwtico'] = oil['dcoilwtico'].ffill().bfill()

In [51]:
oil.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   datetime64[ns]
 1   dcoilwtico  1218 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 19.2 KB

In [52]:
train_data = pd.merge(train_data, stores, on='store_nbr', how='left')
test_data = pd.merge(test_data, stores, on='store_nbr', how='left')

In [53]:
train_data = pd.merge(train_data, oil, on='date', how='left')
test_data = pd.merge(test_data, oil, on='date', how='left')

In [54]:
train_data

,id,date,store_nbr,family,sales,onpromotion,city,state,type,cluster,dcoilwtico
0,0,2013-01-01,1,AUTOMOTIVE,0.000,0,Quito,Pichincha,D,13,93.14
1,1,2013-01-01,1,BABY CARE,0.000,0,Quito,Pichincha,D,13,93.14
2,2,2013-01-01,1,BEAUTY,0.000,0,Quito,Pichincha,D,13,93.14
3,3,2013-01-01,1,BEVERAGES,0.000,0,Quito,Pichincha,D,13,93.14
4,4,2013-01-01,1,BOOKS,0.000,0,Quito,Pichincha,D,13,93.14
...,...,...,...,...,...,...,...,...,...,...,...
3000883,3000883,2017-08-15,9,POULTRY,438.133,0,Quito,Pichincha,B,6,47.57
3000884,3000884,2017-08-15,9,PREPARED FOODS,154.553,1,Quito,Pichincha,B,6,47.57
3000885,3000885,2017-08-15,9,PRODUCE,2419.729,148,Quito,Pichincha,B,6,47.57
3000886,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8,Quito,Pichincha,B,6,47.57
3000887,3000887,2017-08-15,9,SEAFOOD,16.000,0,Quito,Pichincha,B,6,47.57

In [55]:
train_data_idx = len(train_data)

In [56]:
df = pd.concat([train_data, test_data], axis=0, ignore_index=True)
df = df.sort_values(['date', 'store_nbr', 'family']).reset_index(drop=True)

In [57]:
df = pd.merge(df, transactions, on=['date', 'store_nbr'], how='left')

In [58]:
df['transactions'] = df['transactions'].fillna(0)

In [59]:
df['transactions_lag_16'] = df.groupby('store_nbr')['transactions'].transform(lambda x: x.shift(16))
df['transactions_lag_30'] = df.groupby('store_nbr')['transactions'].transform(lambda x: x.shift(30))

In [60]:
df['transactions_roll_mean_7'] = df.groupby('store_nbr')['transactions_lag_16'].transform(lambda x: x.rolling(7).mean())
df['transactions_roll_std_7'] = df.groupby('store_nbr')['transactions_lag_16'].transform(lambda x: x.rolling(7).std())

In [61]:
df['transactions_lag_16'] = df['transactions_lag_16'].fillna(df['transactions_lag_16'].mean())
df['transactions_lag_30'] = df['transactions_lag_30'].fillna(df['transactions_lag_30'].mean())
df['transactions_roll_mean_7'] = df['transactions_roll_mean_7'].fillna(df['transactions_roll_mean_7'].mean())
df['transactions_roll_std_7'] = df['transactions_roll_std_7'].fillna(df['transactions_roll_std_7'].mean())

df['dcoilwtico'] = df['dcoilwtico'].fillna(df['dcoilwtico'].mean())

In [62]:
df['dayofweek'] = df['date'].dt.dayofweek
df['day'] = df['date'].dt.day
df['month'] = df['date'].dt.month
df['is_salary_day'] = df['day'].isin([15, 16, 30, 31]).astype(int)

In [63]:
df = df.drop(columns=['transactions'])

train_final = df.iloc[:train_data_idx].copy()
test_final = df.iloc[train_data_idx:].copy()

In [64]:
train_final

,id,date,store_nbr,family,sales,onpromotion,city,state,type,cluster,dcoilwtico,transactions_lag_16,transactions_lag_30,transactions_roll_mean_7,transactions_roll_std_7,dayofweek,day,month,is_salary_day
0,0,2013-01-01,1,AUTOMOTIVE,0.000,0,Quito,Pichincha,D,13,93.14,1541.604652,1541.989572,1541.768831,18.043303,1,1,1,0
1,1,2013-01-01,1,BABY CARE,0.000,0,Quito,Pichincha,D,13,93.14,1541.604652,1541.989572,1541.768831,18.043303,1,1,1,0
2,2,2013-01-01,1,BEAUTY,0.000,0,Quito,Pichincha,D,13,93.14,1541.604652,1541.989572,1541.768831,18.043303,1,1,1,0
3,3,2013-01-01,1,BEVERAGES,0.000,0,Quito,Pichincha,D,13,93.14,1541.604652,1541.989572,1541.768831,18.043303,1,1,1,0
4,4,2013-01-01,1,BOOKS,0.000,0,Quito,Pichincha,D,13,93.14,1541.604652,1541.989572,1541.768831,18.043303,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3000883,3000751,2017-08-15,54,POULTRY,59.619,0,El Carmen,Manabi,C,3,47.57,802.000000,818.000000,802.000000,0.000000,1,15,8,1
3000884,3000752,2017-08-15,54,PREPARED FOODS,94.000,0,El Carmen,Manabi,C,3,47.57,802.000000,818.000000,802.000000,0.000000,1,15,8,1
3000885,3000753,2017-08-15,54,PRODUCE,915.371,76,El Carmen,Manabi,C,3,47.57,802.000000,802.000000,802.000000,0.000000,1,15,8,1
3000886,3000754,2017-08-15,54,SCHOOL AND OFFICE SUPPLIES,0.000,0,El Carmen,Manabi,C,3,47.57,802.000000,802.000000,802.000000,0.000000,1,15,8,1
3000887,3000755,2017-08-15,54,SEAFOOD,3.000,0,El Carmen,Manabi,C,3,47.57,802.000000,802.000000,802.000000,0.000000,1,15,8,1

In [65]:
# import numpy as np
#
# train_final['target_log'] = np.log1p(train_final['sales'])

In [66]:
train_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 19 columns):
 #   Column                    Dtype
---  ------                    -----
 0   id                        int64
 1   date                      datetime64[ns]
 2   store_nbr                 int64
 3   family                    object
 4   sales                     float64
 5   onpromotion               int64
 6   city                      object
 7   state                     object
 8   type                      object
 9   cluster                   int64
 10  dcoilwtico                float64
 11  transactions_lag_16       float64
 12  transactions_lag_30       float64
 13  transactions_roll_mean_7  float64
 14  transactions_roll_std_7   float64
 15  dayofweek                 int32
 16  day                       int32
 17  month                     int32
 18  is_salary_day             int64
dtypes: datetime64[ns](1), float64(6), int32(3), int64(5), object(4)
memory usage: 400.7+ MB

In [67]:
start_date = '2016-01-01'
train_final = train_final[train_final['date'] >= start_date]

In [68]:
split_date = '2017-07-31'
train_data = train_final[train_final['date'] < split_date]
val_data = train_final[train_final['date'] >= split_date]

In [69]:
features = [
    'store_nbr', 'onpromotion', 'cluster', 'dcoilwtico',
    'transactions_lag_16', 'transactions_lag_30',
    'transactions_roll_mean_7', 'transactions_roll_std_7',
    'dayofweek', 'day', 'month', 'is_salary_day', 'family',
    'city', 'state', 'type'
]

X_train = train_data[features]
y_train = train_data['sales']

X_val = val_data[features]
y_val = val_data['sales']

In [70]:
cat_features = ['family', 'city', 'state', 'type']

In [71]:
from catboost import CatBoostRegressor

model = CatBoostRegressor(
    iterations=1500,
    learning_rate=0.03,
    depth=5,
    eval_metric='MAPE',
    early_stopping_rounds=100,
    random_seed=42
)

model.fit(
    X_train, y_train,
    # eval_set=[(X_val, y_val)],
    cat_features=cat_features,
    # verbose=100
)

0:	learn: 122.8562573	total: 637ms	remaining: 15m 55s
1:	learn: 120.1062339	total: 1.63s	remaining: 20m 19s
2:	learn: 117.4452523	total: 2.42s	remaining: 20m 8s
3:	learn: 114.9293271	total: 3.31s	remaining: 20m 38s
4:	learn: 112.4960575	total: 4.02s	remaining: 20m 3s
5:	learn: 110.0456508	total: 4.72s	remaining: 19m 34s
6:	learn: 107.6653130	total: 5.57s	remaining: 19m 47s
7:	learn: 105.3699180	total: 6.24s	remaining: 19m 22s
8:	learn: 103.4276398	total: 6.78s	remaining: 18m 43s
9:	learn: 101.4464771	total: 7.51s	remaining: 18m 39s
10:	learn: 99.4799059	total: 8.14s	remaining: 18m 22s
11:	learn: 97.4920540	total: 8.72s	remaining: 18m 1s
12:	learn: 95.3988018	total: 9.47s	remaining: 18m 3s
13:	learn: 93.2198620	total: 10.1s	remaining: 17m 56s
14:	learn: 91.4919300	total: 10.8s	remaining: 17m 47s
15:	learn: 88.9641444	total: 11.4s	remaining: 17m 41s
16:	learn: 86.5561750	total: 12.1s	remaining: 17m 34s
17:	learn: 84.2166853	total: 12.7s	remaining: 17m 26s
18:	learn: 81.9584316	total: 13.4s	remaining: 17m 21s
19:	learn: 79.7158327	total: 14.2s	remaining: 17m 27s
20:	learn: 77.5457016	total: 15.2s	remaining: 17m 47s
21:	learn: 75.4327320	total: 16s	remaining: 17m 54s
22:	learn: 73.4238989	total: 16.5s	remaining: 17m 38s
23:	learn: 71.4864028	total: 17.2s	remaining: 17m 37s
24:	learn: 69.5973959	total: 17.9s	remaining: 17m 34s
25:	learn: 67.7550053	total: 18.5s	remaining: 17m 28s
26:	learn: 65.9353239	total: 19.1s	remaining: 17m 21s
27:	learn: 64.2104716	total: 19.7s	remaining: 17m 17s
28:	learn: 62.5380098	total: 20.4s	remaining: 17m 16s
29:	learn: 60.8898231	total: 21.1s	remaining: 17m 13s
30:	learn: 59.7034837	total: 21.6s	remaining: 17m 5s
31:	learn: 58.5920143	total: 22.1s	remaining: 16m 53s
32:	learn: 57.0660715	total: 22.7s	remaining: 16m 50s
33:	learn: 55.5717007	total: 23s	remaining: 16m 33s
34:	learn: 54.5803247	total: 23.2s	remaining: 16m 11s
35:	learn: 53.1904994	total: 23.4s	remaining: 15m 53s
36:	learn: 51.7908722	total: 23.6s	remaining: 15m 34s
37:	learn: 50.4564587	total: 23.9s	remaining: 15m 18s
38:	learn: 49.4951539	total: 24.1s	remaining: 15m 1s
39:	learn: 48.2554523	total: 24.3s	remaining: 14m 46s
40:	learn: 47.1516666	total: 24.5s	remaining: 14m 32s
41:	learn: 46.3446266	total: 24.7s	remaining: 14m 18s
42:	learn: 45.2114158	total: 24.9s	remaining: 14m 3s
43:	learn: 44.3483641	total: 25.1s	remaining: 13m 49s
44:	learn: 43.2463987	total: 25.2s	remaining: 13m 36s
45:	learn: 42.4692831	total: 25.6s	remaining: 13m 28s
46:	learn: 41.4248338	total: 25.8s	remaining: 13m 17s
47:	learn: 40.6960722	total: 26s	remaining: 13m 7s
48:	learn: 39.7060648	total: 26.2s	remaining: 12m 55s
49:	learn: 38.7472602	total: 26.4s	remaining: 12m 45s
50:	learn: 37.7520126	total: 26.6s	remaining: 12m 35s
51:	learn: 36.9761391	total: 26.8s	remaining: 12m 26s
52:	learn: 36.0830779	total: 27s	remaining: 12m 17s
53:	learn: 35.2383417	total: 27.2s	remaining: 12m 8s
54:	learn: 34.3929044	total: 27.4s	remaining: 12m
55:	learn: 33.8503505	total: 27.6s	remaining: 11m 51s
56:	learn: 33.0470404	total: 27.9s	remaining: 11m 45s
57:	learn: 32.2551157	total: 28.1s	remaining: 11m 38s
58:	learn: 31.5010769	total: 28.3s	remaining: 11m 30s
59:	learn: 30.7355014	total: 28.5s	remaining: 11m 24s
60:	learn: 30.0021964	total: 28.7s	remaining: 11m 16s
61:	learn: 29.2857155	total: 28.9s	remaining: 11m 9s
62:	learn: 28.7610120	total: 29.1s	remaining: 11m 2s
63:	learn: 28.1030078	total: 29.3s	remaining: 10m 57s
64:	learn: 27.5144986	total: 29.5s	remaining: 10m 51s
65:	learn: 26.9313316	total: 29.7s	remaining: 10m 45s
66:	learn: 26.3231396	total: 30s	remaining: 10m 40s
67:	learn: 25.7652376	total: 30.2s	remaining: 10m 36s
68:	learn: 25.2264540	total: 30.4s	remaining: 10m 30s
69:	learn: 24.6853092	total: 30.7s	remaining: 10m 26s
70:	learn: 24.1720280	total: 30.9s	remaining: 10m 22s
71:	learn: 23.6802703	total: 31.1s	remaining: 10m 17s
72:	learn: 23.1613143	total: 31.4s	remaining: 10m 13s
73:	learn: 22.6694007	total: 31.6s	remaining: 10m 8s
74:	learn: 22.1913118	total: 31.8s	remaining: 10m 4s
75:	learn: 21.6843009	total: 32s	remaining: 10m
76:	learn: 21.2214549	total: 32.3s	remaining: 9m 57s
77:	learn: 20.7756214	total: 32.5s	remaining: 9m 53s
78:	learn: 20.3355269	total: 32.7s	remaining: 9m 49s
79:	learn: 19.9355232	total: 33s	remaining: 9m 46s
80:	learn: 19.5171905	total: 33.3s	remaining: 9m 42s
81:	learn: 19.2015133	total: 33.5s	remaining: 9m 39s
82:	learn: 18.8919382	total: 33.7s	remaining: 9m 36s
83:	learn: 18.5248816	total: 34s	remaining: 9m 33s
84:	learn: 18.2934797	total: 34.2s	remaining: 9m 29s
85:	learn: 17.8855431	total: 34.4s	remaining: 9m 26s
86:	learn: 17.5459832	total: 34.7s	remaining: 9m 23s
87:	learn: 17.2905516	total: 34.9s	remaining: 9m 20s
88:	learn: 17.0525110	total: 35.1s	remaining: 9m 17s
89:	learn: 16.8243672	total: 35.4s	remaining: 9m 14s
90:	learn: 16.4489775	total: 35.6s	remaining: 9m 11s
91:	learn: 16.0856007	total: 35.9s	remaining: 9m 9s
92:	learn: 15.7708759	total: 36.1s	remaining: 9m 6s
93:	learn: 15.4710709	total: 36.4s	remaining: 9m 4s
94:	learn: 15.1458275	total: 36.6s	remaining: 9m 1s
95:	learn: 14.9187824	total: 36.9s	remaining: 8m 59s
96:	learn: 14.6086572	total: 37.1s	remaining: 8m 56s
97:	learn: 14.3584044	total: 37.2s	remaining: 8m 52s
98:	learn: 14.1818466	total: 37.4s	remaining: 8m 49s
99:	learn: 13.9928730	total: 37.6s	remaining: 8m 46s
100:	learn: 13.7635641	total: 37.8s	remaining: 8m 43s
101:	learn: 13.5818640	total: 38s	remaining: 8m 41s
102:	learn: 13.1719349	total: 38.2s	remaining: 8m 37s
103:	learn: 12.9427860	total: 38.4s	remaining: 8m 35s
104:	learn: 12.7099032	total: 38.6s	remaining: 8m 32s
105:	learn: 12.5484623	total: 38.7s	remaining: 8m 29s
106:	learn: 12.4124662	total: 38.9s	remaining: 8m 26s
107:	learn: 12.2150106	total: 39.1s	remaining: 8m 24s
108:	learn: 11.9822886	total: 39.3s	remaining: 8m 21s
109:	learn: 11.8092450	total: 39.4s	remaining: 8m 18s
110:	learn: 11.5540619	total: 39.6s	remaining: 8m 16s
111:	learn: 11.3818088	total: 39.8s	remaining: 8m 13s
112:	learn: 11.2605268	total: 40s	remaining: 8m 10s
113:	learn: 11.1404300	total: 40.2s	remaining: 8m 8s
114:	learn: 10.9260840	total: 40.3s	remaining: 8m 5s
115:	learn: 10.8135988	total: 40.6s	remaining: 8m 3s
116:	learn: 10.6384494	total: 40.7s	remaining: 8m 1s
117:	learn: 10.5277460	total: 40.9s	remaining: 7m 59s
118:	learn: 10.4229685	total: 41.1s	remaining: 7m 56s
119:	learn: 10.2197884	total: 41.2s	remaining: 7m 54s
120:	learn: 10.1222336	total: 41.4s	remaining: 7m 51s
121:	learn: 9.9794557	total: 41.5s	remaining: 7m 48s
122:	learn: 9.8518807	total: 41.7s	remaining: 7m 46s
123:	learn: 9.7287608	total: 41.9s	remaining: 7m 44s
124:	learn: 9.6282110	total: 42s	remaining: 7m 42s
125:	learn: 9.5161056	total: 42.3s	remaining: 7m 40s
126:	learn: 9.4067322	total: 42.4s	remaining: 7m 38s
127:	learn: 9.3250300	total: 42.6s	remaining: 7m 36s
128:	learn: 9.2523488	total: 42.8s	remaining: 7m 35s
129:	learn: 9.1727383	total: 43s	remaining: 7m 33s
130:	learn: 9.1120320	total: 43.2s	remaining: 7m 31s
131:	learn: 8.9876873	total: 43.4s	remaining: 7m 29s
132:	learn: 8.8911344	total: 43.5s	remaining: 7m 26s
133:	learn: 8.8477851	total: 43.7s	remaining: 7m 25s
134:	learn: 8.8017665	total: 43.9s	remaining: 7m 23s
135:	learn: 8.7223061	total: 44.1s	remaining: 7m 22s
136:	learn: 8.6899111	total: 44.3s	remaining: 7m 20s
137:	learn: 8.6651970	total: 44.4s	remaining: 7m 18s
138:	learn: 8.6445565	total: 44.6s	remaining: 7m 17s
139:	learn: 8.6003463	total: 44.8s	remaining: 7m 15s
140:	learn: 8.5372062	total: 45s	remaining: 7m 13s
141:	learn: 8.5284756	total: 45.2s	remaining: 7m 12s
142:	learn: 8.5228251	total: 45.5s	remaining: 7m 11s
143:	learn: 8.5155935	total: 45.6s	remaining: 7m 9s
144:	learn: 8.4957585	total: 45.9s	remaining: 7m 8s
145:	learn: 8.4970442	total: 46s	remaining: 7m 6s
146:	learn: 8.4896609	total: 46.2s	remaining: 7m 5s
147:	learn: 8.4695739	total: 46.4s	remaining: 7m 4s
148:	learn: 8.5024502	total: 46.6s	remaining: 7m 2s
149:	learn: 8.4902052	total: 46.8s	remaining: 7m
150:	learn: 8.4865502	total: 47s	remaining: 6m 59s
151:	learn: 8.4722863	total: 47.2s	remaining: 6m 58s
152:	learn: 8.4727478	total: 47.4s	remaining: 6m 57s
153:	learn: 8.4400738	total: 47.6s	remaining: 6m 55s
154:	learn: 8.4483591	total: 47.8s	remaining: 6m 54s
155:	learn: 8.4410034	total: 47.9s	remaining: 6m 53s
156:	learn: 8.3946270	total: 48.1s	remaining: 6m 51s
157:	learn: 8.3936484	total: 48.3s	remaining: 6m 50s
158:	learn: 8.3908022	total: 48.5s	remaining: 6m 49s
159:	learn: 8.3972154	total: 48.7s	remaining: 6m 48s
160:	learn: 8.3956995	total: 48.9s	remaining: 6m 46s
161:	learn: 8.3201387	total: 49.1s	remaining: 6m 45s
162:	learn: 8.3229030	total: 49.2s	remaining: 6m 43s
163:	learn: 8.3077769	total: 49.4s	remaining: 6m 42s
164:	learn: 8.3074906	total: 49.6s	remaining: 6m 41s
165:	learn: 8.3250884	total: 49.8s	remaining: 6m 39s
166:	learn: 8.2488379	total: 50s	remaining: 6m 38s
167:	learn: 8.1873701	total: 50.2s	remaining: 6m 37s
168:	learn: 8.1822559	total: 50.4s	remaining: 6m 36s
169:	learn: 8.1192275	total: 50.5s	remaining: 6m 35s
170:	learn: 8.1269635	total: 50.7s	remaining: 6m 34s
171:	learn: 8.1510743	total: 50.9s	remaining: 6m 32s
172:	learn: 8.1663016	total: 51.1s	remaining: 6m 31s
173:	learn: 8.1063459	total: 51.3s	remaining: 6m 30s
174:	learn: 8.0974086	total: 51.4s	remaining: 6m 29s
175:	learn: 8.0589365	total: 51.6s	remaining: 6m 28s
176:	learn: 8.0819101	total: 51.8s	remaining: 6m 26s
177:	learn: 8.0756208	total: 51.9s	remaining: 6m 25s
178:	learn: 8.0861904	total: 52.1s	remaining: 6m 24s
179:	learn: 8.0925275	total: 52.3s	remaining: 6m 23s
180:	learn: 8.0937951	total: 52.5s	remaining: 6m 22s
181:	learn: 8.0228070	total: 52.7s	remaining: 6m 21s
182:	learn: 7.9730601	total: 52.9s	remaining: 6m 20s
183:	learn: 7.9781289	total: 53s	remaining: 6m 19s
184:	learn: 7.9940280	total: 53.2s	remaining: 6m 18s
185:	learn: 8.0113522	total: 53.4s	remaining: 6m 17s
186:	learn: 8.0208685	total: 53.6s	remaining: 6m 16s
187:	learn: 8.0265614	total: 53.8s	remaining: 6m 15s
188:	learn: 8.0322940	total: 54s	remaining: 6m 14s
189:	learn: 8.0404121	total: 54.2s	remaining: 6m 13s
190:	learn: 8.0267334	total: 54.4s	remaining: 6m 12s
191:	learn: 8.0435501	total: 54.5s	remaining: 6m 11s
192:	learn: 8.0494240	total: 54.7s	remaining: 6m 10s
193:	learn: 8.0374639	total: 54.9s	remaining: 6m 9s
194:	learn: 8.0464678	total: 55.1s	remaining: 6m 8s
195:	learn: 8.0531603	total: 55.3s	remaining: 6m 7s
196:	learn: 8.0593069	total: 55.5s	remaining: 6m 6s
197:	learn: 8.0480455	total: 55.6s	remaining: 6m 5s
198:	learn: 8.0669651	total: 55.9s	remaining: 6m 5s
199:	learn: 7.9971263	total: 56s	remaining: 6m 4s
200:	learn: 7.9299207	total: 56.2s	remaining: 6m 3s
201:	learn: 7.9500683	total: 56.4s	remaining: 6m 2s
202:	learn: 7.9529278	total: 56.6s	remaining: 6m 1s
203:	learn: 7.9726515	total: 56.8s	remaining: 6m
204:	learn: 7.9590921	total: 57s	remaining: 6m
205:	learn: 7.9669105	total: 57.2s	remaining: 5m 59s
206:	learn: 7.9814471	total: 57.3s	remaining: 5m 57s
207:	learn: 7.9555675	total: 57.5s	remaining: 5m 57s
208:	learn: 7.9695576	total: 57.6s	remaining: 5m 56s
209:	learn: 7.9965746	total: 57.8s	remaining: 5m 55s
210:	learn: 7.9797568	total: 58s	remaining: 5m 54s
211:	learn: 7.9861521	total: 58.2s	remaining: 5m 53s
212:	learn: 7.9903136	total: 58.3s	remaining: 5m 52s
213:	learn: 8.0064929	total: 58.5s	remaining: 5m 51s
214:	learn: 8.0251591	total: 58.7s	remaining: 5m 50s
215:	learn: 8.0522238	total: 58.9s	remaining: 5m 50s
216:	learn: 8.0570852	total: 59.1s	remaining: 5m 49s
217:	learn: 8.0538693	total: 59.3s	remaining: 5m 48s
218:	learn: 8.0531306	total: 59.5s	remaining: 5m 47s
219:	learn: 8.0707583	total: 59.7s	remaining: 5m 47s
220:	learn: 8.0848890	total: 59.9s	remaining: 5m 46s
221:	learn: 8.0949783	total: 1m	remaining: 5m 45s
222:	learn: 8.0583099	total: 1m	remaining: 5m 44s
223:	learn: 8.0734578	total: 1m	remaining: 5m 44s
224:	learn: 8.0925560	total: 1m	remaining: 5m 43s
225:	learn: 8.0950485	total: 1m	remaining: 5m 42s
226:	learn: 8.0928657	total: 1m 1s	remaining: 5m 42s
227:	learn: 8.0380487	total: 1m 1s	remaining: 5m 41s
228:	learn: 8.0418652	total: 1m 1s	remaining: 5m 40s
229:	learn: 8.0279845	total: 1m 1s	remaining: 5m 39s
230:	learn: 8.0390516	total: 1m 1s	remaining: 5m 38s
231:	learn: 8.0469668	total: 1m 2s	remaining: 5m 41s
232:	learn: 8.0520245	total: 1m 2s	remaining: 5m 42s
233:	learn: 7.9663107	total: 1m 3s	remaining: 5m 44s
234:	learn: 8.0022906	total: 1m 4s	remaining: 5m 45s
235:	learn: 8.0023106	total: 1m 4s	remaining: 5m 47s
236:	learn: 8.0058738	total: 1m 5s	remaining: 5m 48s
237:	learn: 7.9495610	total: 1m 6s	remaining: 5m 49s
238:	learn: 7.9783195	total: 1m 7s	remaining: 5m 56s
239:	learn: 7.9905836	total: 1m 8s	remaining: 5m 57s
240:	learn: 7.9258298	total: 1m 8s	remaining: 5m 57s
241:	learn: 7.9598716	total: 1m 8s	remaining: 5m 58s
242:	learn: 7.9693304	total: 1m 9s	remaining: 5m 58s
243:	learn: 7.9395772	total: 1m 10s	remaining: 6m
244:	learn: 7.8778777	total: 1m 10s	remaining: 6m 1s
245:	learn: 7.8958509	total: 1m 11s	remaining: 6m 3s
246:	learn: 7.8877465	total: 1m 11s	remaining: 6m 4s
247:	learn: 7.9030865	total: 1m 12s	remaining: 6m 5s
248:	learn: 7.9177961	total: 1m 12s	remaining: 6m 6s
249:	learn: 7.9280148	total: 1m 13s	remaining: 6m 8s
250:	learn: 7.8803850	total: 1m 14s	remaining: 6m 9s
251:	learn: 7.9028109	total: 1m 14s	remaining: 6m 11s
252:	learn: 7.9076021	total: 1m 15s	remaining: 6m 12s
253:	learn: 7.8973189	total: 1m 16s	remaining: 6m 14s
254:	learn: 7.9033972	total: 1m 17s	remaining: 6m 16s
255:	learn: 7.8608520	total: 1m 17s	remaining: 6m 16s
256:	learn: 7.8062675	total: 1m 18s	remaining: 6m 17s
257:	learn: 7.8148356	total: 1m 18s	remaining: 6m 19s
258:	learn: 7.8429399	total: 1m 19s	remaining: 6m 20s
259:	learn: 7.8257117	total: 1m 19s	remaining: 6m 21s
260:	learn: 7.8439421	total: 1m 20s	remaining: 6m 21s
261:	learn: 7.8338813	total: 1m 21s	remaining: 6m 23s
262:	learn: 7.8370224	total: 1m 21s	remaining: 6m 24s
263:	learn: 7.8037521	total: 1m 22s	remaining: 6m 25s
264:	learn: 7.8073603	total: 1m 23s	remaining: 6m 26s
265:	learn: 7.8042302	total: 1m 23s	remaining: 6m 28s
266:	learn: 7.8148472	total: 1m 24s	remaining: 6m 30s
267:	learn: 7.7590493	total: 1m 25s	remaining: 6m 31s
268:	learn: 7.7841029	total: 1m 25s	remaining: 6m 32s
269:	learn: 7.7508473	total: 1m 26s	remaining: 6m 35s
270:	learn: 7.7191719	total: 1m 27s	remaining: 6m 36s
271:	learn: 7.6936364	total: 1m 28s	remaining: 6m 37s
272:	learn: 7.6994093	total: 1m 28s	remaining: 6m 38s
273:	learn: 7.7003222	total: 1m 29s	remaining: 6m 39s
274:	learn: 7.6926579	total: 1m 30s	remaining: 6m 40s
275:	learn: 7.7003706	total: 1m 30s	remaining: 6m 42s
276:	learn: 7.6819896	total: 1m 31s	remaining: 6m 43s
277:	learn: 7.6360235	total: 1m 31s	remaining: 6m 44s
278:	learn: 7.6368080	total: 1m 32s	remaining: 6m 46s
279:	learn: 7.6283280	total: 1m 33s	remaining: 6m 46s
280:	learn: 7.6307736	total: 1m 34s	remaining: 6m 48s
281:	learn: 7.6238836	total: 1m 34s	remaining: 6m 48s
282:	learn: 7.6036989	total: 1m 35s	remaining: 6m 49s
283:	learn: 7.6069822	total: 1m 35s	remaining: 6m 50s
284:	learn: 7.6114793	total: 1m 36s	remaining: 6m 51s
285:	learn: 7.6085129	total: 1m 37s	remaining: 6m 52s
286:	learn: 7.5912078	total: 1m 37s	remaining: 6m 53s
287:	learn: 7.5946586	total: 1m 38s	remaining: 6m 53s
288:	learn: 7.6156564	total: 1m 38s	remaining: 6m 54s
289:	learn: 7.6233656	total: 1m 39s	remaining: 6m 55s
290:	learn: 7.5934821	total: 1m 40s	remaining: 6m 56s
291:	learn: 7.5566885	total: 1m 40s	remaining: 6m 57s
292:	learn: 7.5631091	total: 1m 41s	remaining: 6m 59s
293:	learn: 7.5523412	total: 1m 42s	remaining: 7m
294:	learn: 7.5590274	total: 1m 43s	remaining: 7m 1s
295:	learn: 7.5822970	total: 1m 43s	remaining: 7m 2s
296:	learn: 7.5556441	total: 1m 44s	remaining: 7m 3s
297:	learn: 7.5181179	total: 1m 45s	remaining: 7m 4s
298:	learn: 7.5104244	total: 1m 45s	remaining: 7m 5s
299:	learn: 7.5329247	total: 1m 46s	remaining: 7m 6s
300:	learn: 7.4914545	total: 1m 47s	remaining: 7m 7s
301:	learn: 7.4464972	total: 1m 48s	remaining: 7m 9s
302:	learn: 7.4438788	total: 1m 48s	remaining: 7m 9s
303:	learn: 7.4454629	total: 1m 49s	remaining: 7m 10s
304:	learn: 7.4491314	total: 1m 50s	remaining: 7m 11s
305:	learn: 7.4579939	total: 1m 50s	remaining: 7m 12s
306:	learn: 7.4422482	total: 1m 51s	remaining: 7m 13s
307:	learn: 7.4073631	total: 1m 52s	remaining: 7m 14s
308:	learn: 7.3776728	total: 1m 52s	remaining: 7m 14s
309:	learn: 7.3551924	total: 1m 53s	remaining: 7m 15s
310:	learn: 7.3482677	total: 1m 54s	remaining: 7m 16s
311:	learn: 7.3508297	total: 1m 54s	remaining: 7m 17s
312:	learn: 7.3229984	total: 1m 55s	remaining: 7m 18s
313:	learn: 7.3275848	total: 1m 56s	remaining: 7m 18s
314:	learn: 7.3316650	total: 1m 56s	remaining: 7m 19s
315:	learn: 7.3337106	total: 1m 57s	remaining: 7m 20s
316:	learn: 7.3152266	total: 1m 58s	remaining: 7m 20s
317:	learn: 7.3297116	total: 1m 58s	remaining: 7m 21s
318:	learn: 7.3336998	total: 1m 59s	remaining: 7m 22s
319:	learn: 7.3449433	total: 2m	remaining: 7m 23s
320:	learn: 7.3561069	total: 2m	remaining: 7m 24s
321:	learn: 7.3644379	total: 2m 2s	remaining: 7m 26s
322:	learn: 7.3673615	total: 2m 2s	remaining: 7m 28s
323:	learn: 7.3769098	total: 2m 3s	remaining: 7m 28s
324:	learn: 7.3013741	total: 2m 4s	remaining: 7m 29s
325:	learn: 7.3083336	total: 2m 5s	remaining: 7m 30s
326:	learn: 7.2949283	total: 2m 5s	remaining: 7m 31s
327:	learn: 7.3048459	total: 2m 6s	remaining: 7m 31s
328:	learn: 7.3042800	total: 2m 6s	remaining: 7m 31s
329:	learn: 7.3061315	total: 2m 7s	remaining: 7m 31s
330:	learn: 7.3059709	total: 2m 7s	remaining: 7m 30s
331:	learn: 7.2791855	total: 2m 7s	remaining: 7m 29s
332:	learn: 7.2832644	total: 2m 8s	remaining: 7m 28s
333:	learn: 7.2958669	total: 2m 8s	remaining: 7m 28s
334:	learn: 7.2962309	total: 2m 8s	remaining: 7m 27s
335:	learn: 7.2971659	total: 2m 8s	remaining: 7m 26s
336:	learn: 7.2769329	total: 2m 9s	remaining: 7m 25s
337:	learn: 7.3148736	total: 2m 9s	remaining: 7m 25s
338:	learn: 7.3087044	total: 2m 9s	remaining: 7m 24s
339:	learn: 7.3173898	total: 2m 9s	remaining: 7m 23s
340:	learn: 7.3209168	total: 2m 10s	remaining: 7m 22s
341:	learn: 7.3104047	total: 2m 10s	remaining: 7m 22s
342:	learn: 7.3131292	total: 2m 10s	remaining: 7m 21s
343:	learn: 7.2712595	total: 2m 11s	remaining: 7m 20s
344:	learn: 7.2302236	total: 2m 11s	remaining: 7m 19s
345:	learn: 7.2348976	total: 2m 11s	remaining: 7m 19s
346:	learn: 7.2428224	total: 2m 12s	remaining: 7m 18s
347:	learn: 7.2439388	total: 2m 12s	remaining: 7m 18s
348:	learn: 7.2466179	total: 2m 12s	remaining: 7m 17s
349:	learn: 7.2361982	total: 2m 12s	remaining: 7m 16s
350:	learn: 7.2263208	total: 2m 13s	remaining: 7m 16s
351:	learn: 7.2506940	total: 2m 13s	remaining: 7m 15s
352:	learn: 7.2460477	total: 2m 13s	remaining: 7m 14s
353:	learn: 7.2197806	total: 2m 14s	remaining: 7m 13s
354:	learn: 7.2209970	total: 2m 14s	remaining: 7m 13s
355:	learn: 7.2242032	total: 2m 14s	remaining: 7m 12s
356:	learn: 7.1890881	total: 2m 14s	remaining: 7m 11s
357:	learn: 7.1483713	total: 2m 15s	remaining: 7m 10s
358:	learn: 7.1855481	total: 2m 15s	remaining: 7m 9s
359:	learn: 7.2048588	total: 2m 15s	remaining: 7m 8s
360:	learn: 7.1769662	total: 2m 15s	remaining: 7m 7s
361:	learn: 7.1754151	total: 2m 15s	remaining: 7m 6s
362:	learn: 7.1620859	total: 2m 15s	remaining: 7m 5s
363:	learn: 7.1629297	total: 2m 16s	remaining: 7m 4s
364:	learn: 7.1389073	total: 2m 16s	remaining: 7m 3s
365:	learn: 7.1091413	total: 2m 16s	remaining: 7m 2s
366:	learn: 7.0995218	total: 2m 16s	remaining: 7m 1s
367:	learn: 7.0955994	total: 2m 16s	remaining: 7m
368:	learn: 7.0950116	total: 2m 16s	remaining: 6m 59s
369:	learn: 7.0919690	total: 2m 16s	remaining: 6m 58s
370:	learn: 7.1068842	total: 2m 17s	remaining: 6m 57s
371:	learn: 7.1214901	total: 2m 17s	remaining: 6m 56s
372:	learn: 7.1064731	total: 2m 17s	remaining: 6m 55s
373:	learn: 7.1469082	total: 2m 17s	remaining: 6m 54s
374:	learn: 7.1523969	total: 2m 17s	remaining: 6m 53s
375:	learn: 7.1455871	total: 2m 18s	remaining: 6m 52s

CatBoostRegressor(depth=5, early_stopping_rounds=100, eval_metric='MAPE', iterations=1500, learning_rate=0.03, loss_function='RMSE', random_seed=42)

In [74]:
import numpy as np
from sklearn.metrics import mean_absolute_percentage_error, mean_absolute_error

y_pred = model.predict(X_val)
y_pred = np.clip(y_pred, 0, None)

mae = mean_absolute_error(y_val, y_pred)
# mape = mean_absolute_percentage_error(y_val, y_pred)

print(f'В среднем отклонение на {mae:.2f} единицы выручки')
wmape = np.sum(np.abs(y_val - y_pred)) / np.sum(y_val)
print(f'WMAPE: {wmape * 100:.2f}%')

В среднем отклонение на 102.76 единицы выручки
WMAPE: 22.00%